import{useEffect,useState}from'react';import{Link}from'react-router-dom';import{ArrowRight,BookOpen,ClipboardPen,Download,IndianRupee,Headphones,MapPinned,Microscope,Users,HeartPulse,Library,BriefcaseBusiness,ShieldCheck,ChevronLeft,ChevronRight,Quote}from'lucide-react';import{institutions}from'../data/institutions';import{courses}from'../data/coursesPremium';import{facilities}from'../data/facilitiesPremium';import{news}from'../data/news';import{notices}from'../data/notices';import{testimonials}from'../data/testimonials';import{gallery}from'../data/galleryPremium';import{siteSettings}from'../data/siteSettings';import{SectionHeading,InstitutionCard,CourseCard,EnquiryForm,LightboxGrid}from'../components/UI';import VisualDiscovery from'../components/VisualDiscovery';
const slides=[{title:'Build a Career That Makes a Difference',text:'Professional education in Nursing, Pharmacy, Paramedical Sciences, Ayurveda and School Education.',image:'/assets/images/nursing-hero.jpg'},{title:'Learn Through Knowledge, Practice and Care',text:'Industry-focused education supported by practical laboratories, experienced faculty and clinical exposure.',image:'/assets/images/pharmacy-hero.jpg'},{title:'Admissions Open for the New Academic Session',text:'Take the first step towards a rewarding career in healthcare and professional education.',image:'/assets/images/students.jpg'}];
const quick=[[ClipboardPen,'Apply Online','/apply'],[BookOpen,'Explore Courses','/courses'],[Download,'Download Prospectus','/downloads'],[IndianRupee,'Fee Information','/admissions'],[Headphones,'Admission Enquiry','/enquiry'],[MapPinned,'Visit Campus','/contact']];
export default function Home(){const[slide,setSlide]=useState(0);const[cat,setCat]=useState('All');const[test,setTest]=useState(0);useEffect(()=>{const x=setInterval(()=>setSlide(s=>(s+1)%3),6500);return()=>clearInterval(x)},[]);const visible=cat==='All'?courses.slice(0,8):courses.filter(x=>x.category===cat).slice(0,8);return <>
<section className="hero"><img src={slides[slide].image} alt="STech students in a professional learning environment"/><div className="herooverlay"/><div className="shell relative z-10 grid min-h-[610px] items-center gap-10 py-16 lg:grid-cols-[1fr_350px]"><div className="text-white"><p className="eyebrow !text-gold">Admissions & academic session information</p><h1 className="max-w-3xl font-serif text-5xl leading-[1.08] md:text-6xl">{slides[slide].title}</h1><p className="mt-5 max-w-xl text-base leading-7 text-white/80">{slides[slide].text}</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn-primary" to="/courses">Explore courses</Link><Link className="btn-light" to="/apply">Apply for admission</Link></div><div className="mt-10 flex items-center gap-3"><button onClick={()=>setSlide((slide+2)%3)} className="heronav"><ChevronLeft/></button>{slides.map((_,i)=><button key={i} onClick={()=>setSlide(i)} className={`h-2 rounded-full transition-all ${slide===i?'w-8 bg-gold':'w-2 bg-white/60'}`} aria-label={`Slide ${i+1}`}/>) }<button onClick={()=>setSlide((slide+1)%3)} className="heronav"><ChevronRight/></button></div></div><div className="hidden rounded-xl bg-white p-6 shadow-2xl lg:block"><h2 className="mb-4 flex items-center gap-2 font-serif text-xl text-deepnavy"><Headphones className="text-maroon"/> Enquire now</h2><EnquiryForm compact/></div></div></section>
<div className="shell relative z-20 -mt-9"><div className="grid overflow-hidden rounded-xl bg-white shadow-soft sm:grid-cols-3 lg:grid-cols-6">{quick.map(([Icon,n,p])=><Link key={n} to={p} className="quick"><Icon/><span>{n}</span></Link>)}</div></div>
<VisualDiscovery/>
<section className="section"><div className="shell grid items-center gap-12 lg:grid-cols-2"><div className="relative"><img className="h-[430px] w-full rounded-xl object-cover" src="/assets/images/campus.jpg" alt="STech campus building"/><div className="absolute -bottom-5 left-5 rounded-lg bg-white p-4 shadow-soft"><ShieldCheck className="inline text-gold"/> <b className="ml-2 text-sm text-deepnavy">A trusted learning environment</b></div></div><div><SectionHeading eyebrow="About STech Group" title="Education, Healthcare and Professional Excellence Under One Group" desc="STech Group brings together education across school, nursing, pharmacy, paramedical sciences, Ayurveda and healthcare. Our approach connects academic learning with practical experience, ethical values and student development."/><div className="grid gap-4 sm:grid-cols-2">{[['Career-oriented education',BriefcaseBusiness],['Practical learning environment',Microscope],['Experienced faculty',Users],['Student-focused development',HeartPulse]].map(([x,I])=><div className="feature" key={x}><I/>{x}</div>)}</div><div className="mt-7 flex gap-3"><Link className="btn-primary" to="/about">Know more</Link><Link className="btn-secondary" to="/institutions">Our institutions</Link></div></div></div></section>
<section className="section bg-soft"><div className="shell"><SectionHeading eyebrow="Our institutions" title="Multiple Institutions. One Commitment." desc="Distinct academic environments united by a shared commitment to responsible education and care."/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{institutions.map(x=><InstitutionCard key={x.slug} item={x}/>)}</div></div></section>
<section className="section"><div className="shell"><SectionHeading center eyebrow="Explore programmes" title="Find the Right Programme for Your Future" desc="Course details are editable and should be verified before publication."/><div className="filterbar">{['All','School','Nursing','Pharmacy','Paramedical','Ayurveda','Certificate Courses'].map(x=><button onClick={()=>setCat(x)} className={cat===x?'active':''} key={x}>{x}</button>)}</div><div className="mt-7 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{visible.map(x=><CourseCard key={x.slug} course={x}/>)}</div></div></section>
<section className="section bg-deepnavy text-white"><div className="shell grid items-center gap-10 lg:grid-cols-[1fr_1.5fr]"><div><SectionHeading eyebrow="Why choose STech" title="Shaping Futures with Quality and Care" desc="A learning culture designed to connect concepts, practice, service and personal growth."/><Link className="btn-gold" to="/about">Discover our approach</Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[['Practical Learning',Microscope],['Qualified Faculty',Users],['Clinical Exposure',HeartPulse],['Modern Laboratories',ShieldCheck],['Career Guidance',BriefcaseBusiness],['Student Support',Headphones]].map(([x,I])=><div className="darkfeature" key={x}><I/><b>{x}</b><small>Purposeful guidance and an applied learning environment.</small></div>)}</div></div></section>
<section className="section overflow-hidden"><div className="shell"><SectionHeading eyebrow="Campus facilities" title="Spaces Made for Learning and Growth"/><div className="flex gap-5 overflow-x-auto pb-4">{facilities.map(x=><Link to="/facilities" className="facility" key={x.name}><img src={x.image} alt={x.name}/><b>{x.name}</b></Link>)}</div></div></section>
<section className="impact-strip"><div className="shell"><div className="impact-intro"><p className="eyebrow">Our academic ecosystem</p><h2>One group. Multiple paths to a meaningful future.</h2><p>Verified institutional figures will be published after administrative review. Until then, explore the breadth of learning environments across STech Group.</p></div><div className="impact-grid">{siteSettings.stats.map(([label,value],i)=><article key={label}><span>{String(i+1).padStart(2,'0')}</span><div><b>{label}</b><small>{value||'Verified figure coming soon'}</small></div></article>)}</div></div></section>
<section className="section bg-cream"><div className="shell grid gap-10 lg:grid-cols-2"><div><SectionHeading eyebrow="Leadership message" title="Education Guided by Ethics, Knowledge and Care"/><div className="flex gap-5"><div className="leadership-mark" aria-hidden="true">“</div><div><p className="text-sm leading-7 text-muted">“Our purpose is to nurture responsible learners who combine knowledge with skill, empathy and integrity. We remain committed to creating a supportive environment for academic and professional growth.”</p><b className="mt-3 block text-deepnavy">Leadership, STech Group</b><small className="text-muted">Chairperson / Director</small></div></div></div><div><SectionHeading eyebrow="News, notices & events" title="Stay Connected with STech"/><div className="space-y-3">{news.slice(0,3).map(x=><Link to={`/news/${x.slug}`} className="newsrow" key={x.slug}><span>{x.date}</span><b>{x.title}</b><ArrowRight/></Link>)}</div><Link className="textlink mt-5" to="/news-events">View all news & events <ArrowRight/></Link></div></div></section>
<section className="section"><div className="shell"><SectionHeading center eyebrow="Student life" title="Learning Beyond the Classroom"/><LightboxGrid items={gallery}/><div className="mt-8 text-center"><Link className="btn-primary" to="/campus-life">Explore campus life</Link></div></div></section>
<section className="section bg-soft"><div className="shell"><SectionHeading center eyebrow="Student testimonials" title="What Our Students Say" desc="Sample testimonials below must be replaced with verified student reviews before publication."/><div className="mx-auto max-w-3xl rounded-xl bg-white p-8 text-center shadow-soft"><Quote className="mx-auto text-gold" size={38}/><p className="mt-5 font-serif text-xl leading-8 text-deepnavy">“{testimonials[test].quote}”</p><b className="mt-5 block">{testimonials[test].name}</b><small className="text-muted">{testimonials[test].course} · {testimonials[test].batch}</small><div className="mt-6 flex justify-center gap-2">{testimonials.map((_,i)=><button key={i} onClick={()=>setTest(i)} className={`h-2 w-8 rounded ${i===test?'bg-maroon':'bg-line'}`}/>)}</div></div></div></section>
<section className="bg-maroon py-14 text-white"><div className="shell flex flex-col items-center justify-between gap-7 text-center lg:flex-row lg:text-left"><div><p className="eyebrow !text-gold">Admissions</p><h2 className="font-serif text-3xl md:text-4xl">Begin Your Journey with STech Group</h2><p className="mt-2 text-white/70">Connect with our admission team to find the right course for your goals.</p></div><div className="flex flex-wrap justify-center gap-3"><Link className="btn-gold" to="/apply">Apply now</Link><Link className="btn-light" to="/contact">Call admission team</Link></div></div></section>
</>}





