import{useState}from'react';import{Link}from'react-router-dom';import{ArrowRight,Clock,GraduationCap,X,ChevronDown}from'lucide-react';
export const SectionHeading=({eyebrow,title,desc,center=false})=><div className={`${center?'mx-auto text-center':' '} mb-8 max-w-2xl`}><p className="eyebrow">{eyebrow}</p><h2 className="heading">{title}</h2>{desc&&<p className="mt-3 text-sm leading-6 text-muted">{desc}</p>}</div>;
export const InstitutionCard=({item})=><article className="card group"><div className="h-48 overflow-hidden"><img src={item.image} alt={item.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/></div><div className="p-5"><h3 className="font-serif text-xl text-deepnavy">{item.name}</h3><p className="mt-2 min-h-16 text-sm leading-6 text-muted">{item.short}</p><div className="mt-4 flex justify-between border-t border-line pt-4"><Link className="textlink" to={`/institutions/${item.slug}`}>Explore <ArrowRight size={14}/></Link><Link className="text-xs font-semibold text-navy" to={`/courses?category=${item.slug}`}>Courses</Link></div></div></article>;
export const CourseCard=({course})=><article className="card p-5"><span className="tag">{course.category}</span><h3 className="mt-4 font-serif text-xl text-deepnavy">{course.name}</h3><div className="mt-4 space-y-2 text-sm text-muted"><p className="flex gap-2"><Clock size={16} className="text-maroon"/> {course.duration}</p><p className="flex gap-2"><GraduationCap size={16} className="shrink-0 text-maroon"/> {course.eligibility}</p></div><div className="mt-5 flex gap-2"><Link to={`/courses/${course.slug}`} className="btn-secondary flex-1">Details</Link><Link to="/apply" className="btn-primary flex-1">Apply</Link></div></article>;
export function FAQ({items}){const[active,setActive]=useState(0);return <div className="space-y-2">{items.map((x,i)=><div className="rounded-lg border border-line bg-white" key={x[0]}><button onClick={()=>setActive(active===i?-1:i)} className="flex w-full items-center justify-between p-4 text-left font-semibold">{x[0]}<ChevronDown className={`transition ${active===i?'rotate-180':''}`} size={18}/></button>{active===i&&<p className="px-4 pb-4 text-sm leading-6 text-muted">{x[1]}</p>}</div>)}</div>}
export function PageHero({eyebrow='STech Group',title,desc,image}){return <section className="relative isolate overflow-hidden bg-deepnavy py-20 text-white"><img className="absolute inset-0 -z-20 h-full w-full object-cover opacity-25" src={image||'/assets/images/students.jpg'} alt="Students learning on campus"/><div className="absolute inset-0 -z-10 bg-deepnavy/60"/><div className="shell"><p className="eyebrow !text-gold">{eyebrow}</p><h1 className="max-w-3xl font-serif text-4xl leading-tight md:text-5xl">{title}</h1>{desc&&<p className="mt-4 max-w-2xl leading-7 text-white/75">{desc}</p>}</div></section>}
export function EnquiryForm({compact=false}){const[done,setDone]=useState(false);const submit=e=>{e.preventDefault();setDone(true)};if(done)return <div className="rounded-lg bg-green-50 p-6 text-center text-[#237A4B]"><b>Thank you for your enquiry.</b><p className="mt-2 text-sm">This is a static demo. Please call or WhatsApp the admission team to continue.</p></div>;return <form onSubmit={submit} className={`grid gap-3 ${compact?'':'sm:grid-cols-2'}`}><label><span>Student name</span><input required className="field" placeholder="Enter full name"/></label><label><span>Mobile number</span><input required className="field" type="tel" placeholder="10-digit number"/></label><label><span>Email address</span><input required className="field" type="email" placeholder="you@example.com"/></label><label><span>Interested institution</span><select className="field"><option>Select institution</option><option>Nursing</option><option>Pharmacy</option><option>Paramedical</option><option>Ayurved</option><option>School</option></select></label><label><span>Course</span><input className="field" placeholder="Course of interest"/></label><label><span>City</span><input className="field" placeholder="Your city"/></label><button className="btn-primary sm:col-span-2" type="submit">Submit enquiry</button></form>}
export function LightboxGrid({items}){const[selected,setSelected]=useState(null);return <><div className="gallerygrid">{items.map(x=><button key={x.id} onClick={()=>setSelected(x)} className="group relative overflow-hidden rounded-lg"><img src={x.image} alt={x.title}/><span>{x.title}</span></button>)}</div>{selected&&<div className="modal" onClick={()=>setSelected(null)}><button className="absolute right-5 top-5 text-white"><X/></button><img className="max-h-[85vh] max-w-[90vw]" src={selected.image} alt={selected.title}/></div>}</>}

